In [1]:
import numpy as np

In [9]:
#The Basic
a = np.array([1,2,3], dtype='int8')
b = np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]])

#print
print(b)

#print Dimension
print("Dimension", a.ndim)

#print type/size
print("Type", b.dtype, "Size", b.itemsize, "bytes")

#get shape
b.shape

[[1. 2. 3.]
 [4. 5. 6.]]
Dimension 1
Type float64 Size 8 bytes


(2, 3)

In [35]:
#Acessing/Changing Specific Elements
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a.shape
#Get Element
a[0,3]
#Get Row
a[0,:]
#Get Column
a[:,2]
#[startindex:endindex:stepsize]
a[0, 1: -1: 2]
#3d Example
b = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
#specific element (outside in)
b[0,1,1]
b[:,:,1]
#replace
b[:,:,1] = [4,5,6]
b

array([[[1, 4, 3],
        [4, 5, 6],
        [7, 6, 9]]])

In [68]:
#Initializing Different Types of Arrays
a = np.zeros((3,3)) #0
np.ones((4,2,4), dtype='int32') #1
np.full((2,2), 42) #any number
np.full_like(a, 42) #any number with a shape used before
np.full(a.shape, 42) #other way to make
np.random.rand(4,2) # fill with random numbers
np.random.random_sample(b.shape) #fill the shape with random
b = np.random.randint(42, size = (3,3)) #fill with integers
np.identity(3, dtype='int32')
np.repeat(b,3,axis = 0)
c = b.copy() #you have to copy with the function, because if you just insert the value it will be a pointer

In [85]:
#Mathematics
a = np.array([1,2,3,4])
a+2
a-2
a*2
a/2
a**2
np.cos(a)
np.sin(a)
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

In [94]:
#linear Algebra
a = np.ones((2,3))
b = np.full ((3,2), 2)
np.matmul(a,b)
np.matmul(b,a)
c = np.identity(7)
np.linalg.det(c) #Determinant

1.0

In [99]:
#Statistics
values = np.array ([[1,2,3], [4,5,6]])
np.min(values, axis = 1) #axis = 0 == Lines/ axis = 1 == Columns
np.max(values)
np.sum(values)

21

In [121]:
#Reorganizing Arrays
before = np.array ([[1,2,3], [4,5,6]])
after = before.reshape((2,3))
#vertically stacking vector
ba = np.array([1,2,3,4])
be = np.array([5,6,7,8])
np.vstack([ba,be,ba,ba,be])
#Horizontal stack
np.hstack([ba,be,be,be,ba])

array([1, 2, 3, 4, 5, 6, 7, 8, 5, 6, 7, 8, 5, 6, 7, 8, 1, 2, 3, 4])

In [127]:
#load data from file
data = np.genfromtxt('data.txt', delimiter=',')
data.astype('int32')

array([[ 12,   1, 212,  12,   1,   2,  12,   1,  21,   2],
       [ 54,   5,  45,   4,  54,   5,  45,   4,   5,  54],
       [  1,  23,  14,   8,   3,  54,   6,  57,   5,   4]])

In [138]:
#Boolean masking
data > 50
data[data > 50]
np.any(data>50, axis=0)
np.any(data>100, axis=1)

array([ True, False, False])

In [ ]:
#indexing list
a = np.array([1,2,3,4,5,6,7,8,9,1])
a[[1,2,9]]